
name:  JRPN16 Build
run-name: ${{ github.actor }} JRPN16 Build
on: 
    workflow_dispatch:          # Manually

    # push:
    #     branches: [master]
    #     paths-ignore:
    #         - '**/README.md'

jobs:
    macos-build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  architecture: x64
                  # flutter:version: '3.0.0'
            - run: flutter pub get
            - run: flutter config --enable-macos-desktop
            - run: flutter build macos
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn16_macos.app.zip
                path: "build/macos/Build/Products/Release/JRPN 16c.app"
            # - run: flutter build ios --release --no-codesign
