
# See https://github.com/subosito/flutter-action

name:  JRPN16 Build
run-name: ${{ github.actor }} JRPN16 Build
on: 
    workflow_dispatch:          # Manually

    # push:
    #     branches: [master]
    #     paths-ignore:
    #         - '**/README.md'

jobs:
    macos-build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  architecture: x64
                  # flutter:version: '3.0.0'
            - run: flutter pub get
            - run: flutter config --enable-macos-desktop
            - run: flutter build macos
            - run: cd build/macos/Build/Products/Release/ ; zip -r jrpn16_macos.app.zip "JRPN 16c.app"
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn16_macos
                path:  build/macos/Build/Products/Release/jrpn16_macos.app.zip
            - run: flutter build ios --release --no-codesign
            - run: cd build/ios/Release-iphoneos ; zip -r jrpn16_ios.app.zip Runner.app
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn16_ios
                path:  build/ios/Release-iphoneos/jrpn16_ios.app.zip

    apk-and-linux-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v2
              with:
                distribution: 'zulu'
                java-version: '11'
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  # flutter:version: '3.0.0'
            - run: flutter pub get
            - run: flutter build apk
            - run: flutter build linux

    msix-build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  # flutter:version: '3.0.0'
            - run: flutter config --enable-windows-desktop
            - run: flutter build windows
            - run: dart run msix:create
